### ISSUE TITLE
CCU addon is crashing node red

### ISSUE THREAD

**Issue by Marty56** [HM-RedMatic/node-red-contrib-ccu#46]
I am receiving the following error log

`27 Dec 18:51:38 - [info] [mqtt-broker:Sonoff Broker] Connected to broker: mqtt://localhost:1883
27 Dec 18:51:38 - [error] [ccu-connection:localhost] Error: connect ECONNREFUSED 127.0.0.1:8181
27 Dec 18:51:38 - [info] [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
27 Dec 18:51:38 - [info] [ccu-connection:localhost] ReGaHSS http port 1999 connected
27 Dec 18:51:38 - [info] [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
27 Dec 18:51:38 - [error] [ccu-connection:localhost] Error: connect ECONNREFUSED 127.0.0.1:8181
27 Dec 18:51:38 - [info] [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
27 Dec 18:51:38 - [info] [ccu-connection:localhost] ReGaHSS http port 1999 connected
27 Dec 18:51:38 - [info] [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
27 Dec 18:51:38 - [red] Uncaught Exception:
27 Dec 18:51:38 - Error: listen EADDRINUSE: address already in use 127.0.0.1:2048
    at Server.setupListenHandle [as _listen2] (net.js:1294:14)
    at listenInCluster (net.js:1342:12)
    at doListen (net.js:1480:7)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)`

Is there a workarround?

**Comment by hobbyquaker** [comment]
Check mal bitte ob Da eventuell 2 ccu-config Nodes vorhanden sind und lösch ggf. einen (siehe https://github.com/HM-RedMatic/RedMatic/wiki/CCU-Nodes#ccu-connection-node)
Falls das nicht weiterhilft bitte mal ein komplettes Log anhängen (CCU Systemsteuerung -> RedMatic -> Log -> Button Log Download)

**Comment by Marty56** [comment]
WIe gesagt, ich betreibe keine Redmatic, sondern habe Node Red auf einem Mac Installiert und die CCU2 als auf einem anderen Gerät.
Ich kann keinen Knoten löschen (oder weiß nicht wie), weil der Node Red server ja abschmiert und damit kein User Interface zum Löschen da ist.
Kann ich irgendwas über das Terminal machen?

**Comment by hobbyquaker** [comment]
Node-RED speichert seine Flows in `~/.node-red/flows_<hostname>.json`. Entweder da den Config Node von Hand "rausoperieren" oder falls vertretbar einfach die ganze Datei löschen.
